import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { byPosted, getPosts } from "../../utils";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Demo Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Blog powered by Google Docs</h1>
        <div className={styles.grid}>
          {posts.map(({ id, name, slug }) => (
            <Link key={id} href={`/blog/${slug}`}>
              {name}
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const posts = await getPosts();

  return {
    props: {
      posts: posts.filter(byPosted),
    },
  };
}
